#import <AppKit/AppKit.h>
#import <AVFoundation/AVFoundation.h>
#include "synth.h"
#include <array>
#include <cmath>
#include <mutex>

using namespace muew;

static NSColor* C(uint32_t rgb, CGFloat a=1) { return [NSColor colorWithRed:((rgb>>16)&255)/255.0 green:((rgb>>8)&255)/255.0 blue:(rgb&255)/255.0 alpha:a]; }
static void Text(NSString* s, NSRect r, CGFloat size, NSColor* color, NSFontWeight weight=NSFontWeightRegular) {
    [s drawInRect:r withAttributes:@{NSFontAttributeName:[NSFont systemFontOfSize:size weight:weight],NSForegroundColorAttributeName:color}];
}

@interface MUEWView : NSView { @public Synth* synth; std::mutex* lock; }
@property int preset, warpA, warpB;
@property double positionA, positionB, cutoff, resonance, attack, releaseTime, mseg;
@property NSInteger dragKnob; @property NSPoint dragStart; @property double dragValue;
@end

@implementation MUEWView
- (instancetype)initWithFrame:(NSRect)f { if((self=[super initWithFrame:f])){ self.wantsLayer=YES; _preset=3; _warpA=1; _warpB=6; _positionA=.62; _positionB=.28; _cutoff=.58; _resonance=.31; _attack=.12; _releaseTime=.42; _mseg=.67; _dragKnob=-1; } return self; }
- (BOOL)acceptsFirstResponder{return YES;}
- (void)applySound { if(!synth)return; std::lock_guard<std::mutex> g(*lock); VoiceParams p; p.osc1Shape=2;p.osc2Shape=3;p.osc2Level=_positionB;p.osc2Detune=12.02;p.osc1WarpMode=_warpA;p.osc2WarpMode=_warpB;p.osc1Warp=_positionA;p.osc2Warp=.58;p.filterCutoff=80*std::pow(160,_cutoff);p.filterReso=.4+_resonance*7;p.ampA=.002+_attack*1.8;p.ampR=.03+_releaseTime*2;p.mseg1Seconds=.15+_mseg*1.5;p.mseg1Loop=true;synth->setParams(p,{{ModRoute::Source::MSEG1,ModRoute::Dest::Osc1Warp,.75},{ModRoute::Source::LFO2,ModRoute::Dest::Osc2Warp,.25},{ModRoute::Source::MSEG1,ModRoute::Dest::FilterCutoff,2.8}}); }
- (void)panel:(NSRect)r title:(NSString*)title { NSBezierPath* p=[NSBezierPath bezierPathWithRoundedRect:r xRadius:12 yRadius:12];[C(0x151a22) setFill];[p fill];[C(0x29313d) setStroke];p.lineWidth=1;[p stroke];Text(title,NSMakeRect(r.origin.x+16,NSMaxY(r)-30,r.size.width-32,20),11,C(0x8793a3),NSFontWeightSemibold); }
- (void)knobAt:(NSPoint)c radius:(CGFloat)rad value:(double)v label:(NSString*)label accent:(NSColor*)accent { [[NSColor colorWithWhite:.04 alpha:1]setFill];[[NSBezierPath bezierPathWithOvalInRect:NSMakeRect(c.x-rad-3,c.y-rad-3,rad*2+6,rad*2+6)]fill];NSBezierPath*ring=[NSBezierPath bezierPath];[ring appendBezierPathWithArcWithCenter:c radius:rad startAngle:225 endAngle:-45 clockwise:YES];[C(0x303947)setStroke];ring.lineWidth=4;[ring stroke];NSBezierPath*arc=[NSBezierPath bezierPath];[arc appendBezierPathWithArcWithCenter:c radius:rad startAngle:225 endAngle:225-270*v clockwise:YES];[accent setStroke];arc.lineWidth=4;[arc stroke];double a=(225-270*v)*M_PI/180;NSBezierPath*line=[NSBezierPath bezierPath];[line moveToPoint:c];[line lineToPoint:NSMakePoint(c.x+cos(a)*(rad-7),c.y+sin(a)*(rad-7))];[C(0xeaf1f8)setStroke];line.lineWidth=2;[line stroke];Text(label,NSMakeRect(c.x-rad-10,c.y-rad-25,rad*2+20,15),10,C(0xa8b2c1),NSFontWeightMedium); }
- (void)wave:(NSRect)r phase:(double)phase color:(NSColor*)col harmonics:(int)h {NSBezierPath*p=[NSBezierPath bezierPath];for(int i=0;i<240;i++){double x=r.origin.x+r.size.width*i/239.;double q=i/239.;double y=sin(2*M_PI*q);for(int n=2;n<=h;n++)y+=sin(2*M_PI*n*q+phase*n)/(n*1.5);y/=1.5;NSPoint pt=NSMakePoint(x,NSMidY(r)+y*r.size.height*.32);i?[p lineToPoint:pt]:[p moveToPoint:pt];}[col setStroke];p.lineWidth=2;[p stroke];}
- (void)drawRect:(NSRect)dirty { [C(0x0b0e13)setFill];NSRectFill(self.bounds);NSRect b=self.bounds;NSGradient*g=[[NSGradient alloc]initWithStartingColor:C(0x121822) endingColor:C(0x080a0e)];[g drawInRect:NSMakeRect(0,b.size.height-82,b.size.width,82) angle:270];Text(@"MUEW",NSMakeRect(28,b.size.height-59,180,38),28,C(0xf5f7fa),NSFontWeightBold);Text(@"WAVETABLE INSTRUMENT",NSMakeRect(160,b.size.height-52,210,20),11,C(0x5adac8),NSFontWeightSemibold);Text(@"POLYPHONIC  •  UNIVERSAL AUv2",NSMakeRect(b.size.width-280,b.size.height-51,250,18),10,C(0x758192),NSFontWeightMedium);
 CGFloat top=b.size.height-100;[self panel:NSMakeRect(24,top-260,440,260) title:@"OSCILLATORS"];[self panel:NSMakeRect(478,top-260,306,260) title:@"FILTER + AMP"];[self panel:NSMakeRect(798,top-260,b.size.width-822,260) title:@"PRESET BROWSER"];
 NSRect wa=NSMakeRect(46,top-125,190,76),wb=NSMakeRect(252,top-125,190,76);[C(0x0a0d12)setFill];[[NSBezierPath bezierPathWithRoundedRect:wa xRadius:7 yRadius:7]fill];[[NSBezierPath bezierPathWithRoundedRect:wb xRadius:7 yRadius:7]fill];[self wave:wa phase:_positionA color:C(0x5adac8) harmonics:7];[self wave:wb phase:_positionB color:C(0x9d7df2) harmonics:5];Text(@"OSC A  •  SYNC",NSMakeRect(50,top-47,170,16),10,C(0x5adac8),NSFontWeightSemibold);Text(@"OSC B  •  FOLD",NSMakeRect(256,top-47,170,16),10,C(0x9d7df2),NSFontWeightSemibold);
 [self knobAt:NSMakePoint(98,top-194) radius:25 value:_positionA label:@"WARP A" accent:C(0x5adac8)];[self knobAt:NSMakePoint(195,top-194) radius:25 value:_positionB label:@"MIX" accent:C(0x5adac8)];[self knobAt:NSMakePoint(308,top-194) radius:25 value:.58 label:@"WARP B" accent:C(0x9d7df2)];[self knobAt:NSMakePoint(405,top-194) radius:25 value:.51 label:@"DETUNE" accent:C(0x9d7df2)];
 [self knobAt:NSMakePoint(536,top-94) radius:30 value:_cutoff label:@"CUTOFF" accent:C(0xf2ab55)];[self knobAt:NSMakePoint(637,top-94) radius:30 value:_resonance label:@"RESONANCE" accent:C(0xf2ab55)];[self knobAt:NSMakePoint(536,top-200) radius:25 value:_attack label:@"ATTACK" accent:C(0x6cb6ff)];[self knobAt:NSMakePoint(637,top-200) radius:25 value:_releaseTime label:@"RELEASE" accent:C(0x6cb6ff)];[self knobAt:NSMakePoint(732,top-200) radius:25 value:_mseg label:@"MSEG TIME" accent:C(0x5adac8)];
 NSArray*names=@[@"Aerial Glass",@"Bent Circuit",@"Chrome Motion",@"Deep Meridian",@"Fifth Element",@"Hollow Current",@"Night Bloom",@"Prism Keys",@"Soft Engine",@"Vector Choir"];for(int i=0;i<10;i++){CGFloat y=top-53-i*19;if(i==_preset){[C(0x293c3b)setFill];[[NSBezierPath bezierPathWithRoundedRect:NSMakeRect(812,y-2,b.size.width-850,18) xRadius:4 yRadius:4]fill];}Text(names[i],NSMakeRect(820,y,b.size.width-865,15),10,i==_preset?C(0x75ead8):C(0x9ca6b4),i==_preset?NSFontWeightSemibold:NSFontWeightRegular);}
 CGFloat low=top-286;[self panel:NSMakeRect(24,38,b.size.width-48,low-48) title:@"MODULATION + EFFECTS"];NSArray*mods=@[@"ENV 1",@"LFO 1",@"LFO 2",@"MSEG 1"];NSArray*dst=@[@"WARP A",@"CUTOFF",@"WARP B",@"RESO"];for(int i=0;i<4;i++){CGFloat x=48+i*150;[C(i==3?0x21423e:0x202630)setFill];[[NSBezierPath bezierPathWithRoundedRect:NSMakeRect(x,76,130,low-92) xRadius:8 yRadius:8]fill];Text(mods[i],NSMakeRect(x+12,low-42,95,16),11,i==3?C(0x66e2d0):C(0xb9c2ce),NSFontWeightSemibold);Text(dst[i],NSMakeRect(x+12,91,95,15),9,C(0x6f7b8b),NSFontWeightMedium);}CGFloat ex=b.size.width-500;NSArray*fx=@[@"CHORUS",@"DELAY",@"REVERB"];for(int i=0;i<3;i++){CGFloat x=ex+i*145;[C(0x1b222c)setFill];[[NSBezierPath bezierPathWithRoundedRect:NSMakeRect(x,76,125,low-92) xRadius:8 yRadius:8]fill];Text(fx[i],NSMakeRect(x+13,low-42,100,16),10,C(0xf2ab55),NSFontWeightSemibold);[self knobAt:NSMakePoint(x+63,113) radius:20 value:.3+i*.18 label:@"MIX" accent:C(0xf2ab55)];}
 }
- (NSInteger)hitKnob:(NSPoint)p { NSRect b=self.bounds;CGFloat top=b.size.height-100;NSPoint pts[]={ {98,top-194},{195,top-194},{536,top-94},{637,top-94},{536,top-200},{637,top-200},{732,top-200} };for(int i=0;i<7;i++)if(hypot(p.x-pts[i].x,p.y-pts[i].y)<38)return i;return -1;}
- (double)valueFor:(NSInteger)i {double v[]={_positionA,_positionB,_cutoff,_resonance,_attack,_releaseTime,_mseg};return v[i];}
- (void)setKnob:(NSInteger)i value:(double)v {v=fmax(0,fmin(1,v));switch(i){case 0:_positionA=v;break;case 1:_positionB=v;break;case 2:_cutoff=v;break;case 3:_resonance=v;break;case 4:_attack=v;break;case 5:_releaseTime=v;break;case 6:_mseg=v;break;}[self applySound];[self setNeedsDisplay:YES];}
- (void)mouseDown:(NSEvent*)e {NSPoint p=[self convertPoint:e.locationInWindow fromView:nil];_dragKnob=[self hitKnob:p];_dragStart=p;if(_dragKnob>=0)_dragValue=[self valueFor:_dragKnob];else{CGFloat top=self.bounds.size.height-100;if(p.x>798&&p.y>top-255&&p.y<top-35){_preset=fmax(0,fmin(9,(int)((top-35-p.y)/19)));[self setNeedsDisplay:YES];}}}
- (void)mouseDragged:(NSEvent*)e {if(_dragKnob<0)return;NSPoint p=[self convertPoint:e.locationInWindow fromView:nil];[self setKnob:_dragKnob value:_dragValue+(p.y-_dragStart.y)/140.];}
- (void)mouseUp:(NSEvent*)e {_dragKnob=-1;}
- (void)keyDown:(NSEvent*)e {static const char*keys="awsedftgyhujk";const char*c=[e.characters UTF8String];if(c){const char*p=strchr(keys,c[0]);if(p){std::lock_guard<std::mutex>g(*lock);synth->noteOn(48+(int)(p-keys),.85);}}}
- (void)keyUp:(NSEvent*)e {static const char*keys="awsedftgyhujk";const char*c=[e.characters UTF8String];if(c){const char*p=strchr(keys,c[0]);if(p){std::lock_guard<std::mutex>g(*lock);synth->noteOff(48+(int)(p-keys));}}}
@end

@interface AppDelegate:NSObject<NSApplicationDelegate>{NSWindow*w;MUEWView*v;AVAudioEngine*engine;AVAudioSourceNode*source;Synth synth;std::mutex lock;}@end
@implementation AppDelegate
- (void)applicationDidFinishLaunching:(NSNotification*)n {NSRect f=NSMakeRect(0,0,1000,680);w=[[NSWindow alloc]initWithContentRect:f styleMask:NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskMiniaturizable backing:NSBackingStoreBuffered defer:NO];w.title=@"MUEW";w.backgroundColor=C(0x0b0e13);v=[[MUEWView alloc]initWithFrame:f];v->synth=&synth;v->lock=&lock;w.contentView=v;[w center];[w makeKeyAndOrderFront:nil];[w makeFirstResponder:v];synth.init(44100);[v applySound];engine=[AVAudioEngine new];AVAudioFormat*fmt=[[AVAudioFormat alloc]initStandardFormatWithSampleRate:44100 channels:2];source=[[AVAudioSourceNode alloc]initWithRenderBlock:^OSStatus(BOOL*s,const AudioTimeStamp*t,AVAudioFrameCount count,AudioBufferList*out){float*l=(float*)out->mBuffers[0].mData;float*r=(float*)out->mBuffers[1].mData;std::lock_guard<std::mutex>g(lock);synth.renderPlanar(l,r,(int)count);return noErr;}];[engine attachNode:source];[engine connect:source to:engine.mainMixerNode format:fmt];NSError*err=nil;[engine startAndReturnError:&err];}
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication*)s{return YES;}
@end
int main(int argc,const char**argv){@autoreleasepool{NSApplication*app=[NSApplication sharedApplication];app.activationPolicy=NSApplicationActivationPolicyRegular;app.presentationOptions=NSApplicationPresentationAutoHideDock;AppDelegate*d=[AppDelegate new];app.delegate=d;[app activateIgnoringOtherApps:YES];[app run];}return 0;}
