#!/usr/bin/env python3
"""Generate src/factory_bank.h from presets/bank.txt so the AU and the
standalone app embed exactly the authored .muew files, in AU number order."""
import os, sys
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
slugs = [l.strip() for l in open(os.path.join(root, "presets", "bank.txt"))
         if l.strip() and not l.startswith("#")]
out = ["// Generated by scripts/embed_factory_bank.py from presets/bank.txt. Do not edit.",
       "#pragma once", "#include \"preset.h\"", "#include <string>", "#include <vector>", "",
       "namespace muew {", "", "struct FactoryPresetText { const char* slug; const char* text; };", "",
       "inline const FactoryPresetText kFactoryPresetTexts[] = {"]
for s in slugs:
    text = open(os.path.join(root, "presets", s + ".muew")).read()
    if ")MUEW\"" in text: sys.exit("delimiter collision in " + s)
    out.append('    {"%s", R"MUEW(%s)MUEW"},' % (s, text))
out += ["};", "",
        "constexpr int kFactoryPresetCount = (int)(sizeof(kFactoryPresetTexts) / sizeof(kFactoryPresetTexts[0]));",
        "",
        "// Parsed once on first use (never on the audio thread).",
        "inline const std::vector<Preset>& factoryPresets() {",
        "    static const std::vector<Preset> bank = [] {",
        "        std::vector<Preset> v;",
        "        for (const auto& t : kFactoryPresetTexts) { Preset p; p.parse(t.text); v.push_back(p); }",
        "        return v;",
        "    }();",
        "    return bank;",
        "}", "",
        "// Browser category order shown in the UI.",
        "inline const std::vector<std::string>& factoryCategories() {",
        "    static const std::vector<std::string> c{\"Bass\", \"Lead\", \"Pad\", \"Keys\", \"Pluck\", \"Texture\", \"FX\"};",
        "    return c;",
        "}", "", "} // namespace muew", ""]
open(os.path.join(root, "src", "factory_bank.h"), "w").write("\n".join(out))
print("embedded %d presets" % len(slugs))
