// Generated by scripts/embed_factory_bank.py from presets/bank.txt. Do not edit.
#pragma once
#include "preset.h"
#include <string>
#include <vector>

namespace muew {

struct FactoryPresetText { const char* slug; const char* text; };

inline const FactoryPresetText kFactoryPresetTexts[] = {
    {"airy-strings", R"MUEW(muew-preset 2
name Airy Strings
category Pad
author MUEW Factory
tags strings wide slow
osc1Shape 2
osc2Shape 2
osc2Detune 0.12
osc2Level 0.55
filterCutoff 4200
filterReso 0.35
filterMode 0
amp 1.8 1 0.8 2.2
mod 1.5 1 0.4 1.5
lfo1Rate 0.15
lfo1Shape 1
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 1
route 0 3 0.15
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.35 7 14 0.32
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.85 0.35 0.4
)MUEW"},
    {"bright-lead", R"MUEW(muew-preset 2
name Bright Lead
category Lead
author MUEW Factory
tags bright mono-style vibrato
osc1Shape 2
osc2Shape 3
osc2Detune 7
osc2Level 0.45
filterCutoff 6000
filterReso 0.8
filterMode 0
amp 0.01 0.1 0.9 0.15
mod 0.01 0.25 0 0.1
lfo1Rate 5.5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 9
route 1 2 2
route 0 0 0.15
route 2 2 1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.28 0.34 0.35 0.25
reverb 1 0.4 0.5 0.2
)MUEW"},
    {"init-saw", R"MUEW(muew-preset 2
name Init Saw
category Lead
author MUEW Factory
tags init basic
osc1Shape 2
osc2Shape 3
osc2Detune 7
osc2Level 0.5
filterCutoff 8000
filterReso 0.7
filterMode 0
amp 0.005 0.15 0.8 0.3
mod 0.01 0.3 0 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 9
route 1 2 2
route 0 1 0.05
route 2 2 1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"pluck", R"MUEW(muew-preset 2
name Pluck
category Pluck
author MUEW Factory
tags short bright
osc1Shape 2
osc2Shape 4
osc2Detune 0
osc2Level 0.4
filterCutoff 5200
filterReso 0.6
filterMode 0
amp 0.001 0.35 0 0.12
mod 0.001 0.2 0 0.1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 2.5
route 2 2 0.6
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.22 0.28 0.3 0.18
reverb 1 0.35 0.5 0.15
)MUEW"},
    {"punchy-bass", R"MUEW(muew-preset 2
name Punchy Bass
category Bass
author MUEW Factory
tags punchy dry
osc1Shape 3
osc2Shape 2
osc2Detune -12
osc2Level 0.6
filterCutoff 900
filterReso 0.9
filterMode 0
amp 0.002 0.25 0.4 0.08
mod 0.005 0.15 0 0.05
lfo1Rate 2
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 1.2
route 2 2 0.8
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"soft-keys", R"MUEW(muew-preset 2
name Soft Keys
category Keys
author MUEW Factory
tags soft mellow
osc1Shape 1
osc2Shape 0
osc2Detune 0.02
osc2Level 0.5
filterCutoff 3500
filterReso 0.3
filterMode 0
amp 0.01 0.6 0.5 0.4
mod 0.01 0.3 0 0.2
lfo1Rate 4
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 7
route 2 2 0.8
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.4 3 10 0.18
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.5 0.5 0.22
)MUEW"},
    {"sub-bass", R"MUEW(muew-preset 2
name Sub Bass
category Bass
author MUEW Factory
tags sub clean dry
osc1Shape 0
osc2Shape 0
osc2Detune -12
osc2Level 0.4
filterCutoff 400
filterReso 0.2
filterMode 0
amp 0.005 0.1 1 0.1
mod 0.01 0.3 0 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 6
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"warm-pad", R"MUEW(muew-preset 2
name Warm Pad
category Pad
author MUEW Factory
tags warm wide slow
osc1Shape 2
osc2Shape 2
osc2Detune 0.08
osc2Level 0.5
filterCutoff 2400
filterReso 0.4
filterMode 0
amp 1.2 1.5 0.7 1.6
mod 0.8 1.2 0.3 1
lfo1Rate 0.2
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 1.5
route 0 3 0.1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.5 5 12 0.3
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.75 0.4 0.35
)MUEW"},
    {"fold-growl", R"MUEW(muew-preset 2
name Fold Growl
category Bass
author MUEW Factory
tags growl fold aggressive
osc1Shape 3
osc2Shape 2
osc2Detune -12
osc2Level 0.45
filterCutoff 1400
filterReso 1.6
filterMode 0
amp 0.003 0.3 0.7 0.12
mod 0.005 0.4 0.2 0.1
lfo1Rate 3
lfo1Shape 0
lfo2 0.35 1
warp1 6 0.25
warp2 6 0
mseg 0.5 1 5 0 0 0.25 1 0.5 0.1 0.75 0.8 1 0
routes 8
route 4 5 0.55
route 1 2 1.4
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"reese-drift", R"MUEW(muew-preset 2
name Reese Drift
category Bass
author MUEW Factory
tags reese detuned dark
osc1Shape 2
osc2Shape 2
osc2Detune 0.15
osc2Level 0.9
filterCutoff 700
filterReso 1.2
filterMode 0
amp 0.01 0.2 0.9 0.2
mod 0.01 0.3 0 0.2
lfo1Rate 0.3
lfo1Shape 1
lfo2 0.12 0
warp1 2 0
warp2 3 0.3
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 3 2 1.2
route 0 6 0.2
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"sync-bite", R"MUEW(muew-preset 2
name Sync Bite
category Bass
author MUEW Factory
tags sync plucky mid
osc1Shape 2
osc2Shape 4
osc2Detune -12
osc2Level 0.35
filterCutoff 1800
filterReso 1.1
filterMode 0
amp 0.001 0.28 0.5 0.1
mod 0.001 0.22 0 0.1
lfo1Rate 4
lfo1Shape 0
lfo2 0.35 1
warp1 1 0.1
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 9
route 1 5 0.8
route 1 2 1.8
route 2 2 0.5
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"rubber-sub", R"MUEW(muew-preset 2
name Rubber Sub
category Bass
author MUEW Factory
tags sub round bend
osc1Shape 0
osc2Shape 1
osc2Detune -12
osc2Level 0.3
filterCutoff 650
filterReso 0.5
filterMode 0
amp 0.002 0.18 0.85 0.1
mod 0.001 0.12 0 0.05
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0.1
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 5 0.6
route 1 2 0.8
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"glass-sync-lead", R"MUEW(muew-preset 2
name Glass Sync Lead
category Lead
author MUEW Factory
tags sync vibrato bright
osc1Shape 2
osc2Shape 0
osc2Detune 12
osc2Level 0.3
filterCutoff 7000
filterReso 0.9
filterMode 0
amp 0.01 0.2 0.85 0.25
mod 0.05 0.8 0.3 0.3
lfo1Rate 5.2
lfo1Shape 0
lfo2 0.35 1
warp1 1 0.35
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 9
route 1 5 0.5
route 0 0 0.12
route 0 1 0.12
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.33 0.25 0.3 0.2
reverb 1 0.45 0.45 0.18
)MUEW"},
    {"hollow-fifths", R"MUEW(muew-preset 2
name Hollow Fifths
category Lead
author MUEW Factory
tags fifths hollow bandpass
osc1Shape 3
osc2Shape 3
osc2Detune 7
osc2Level 0.6
filterCutoff 1500
filterReso 1.8
filterMode 1
amp 0.02 0.3 0.8 0.3
mod 0.02 0.5 0.2 0.3
lfo1Rate 4.5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 1.5
route 0 0 0.1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.36 0.48 0.4 0.25
reverb 1 0.5 0.4 0.2
)MUEW"},
    {"acid-squelch", R"MUEW(muew-preset 2
name Acid Squelch
category Lead
author MUEW Factory
tags acid resonant squelch
osc1Shape 2
osc2Shape 3
osc2Detune 0
osc2Level 0.2
filterCutoff 500
filterReso 6
filterMode 0
amp 0.002 0.2 0.6 0.08
mod 0.001 0.25 0 0.1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 3.5
route 2 2 0.8
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.24 0.36 0.3 0.15
reverb 0 0.55 0.45 0.28
)MUEW"},
    {"pwm-solo", R"MUEW(muew-preset 2
name PWM Solo
category Lead
author MUEW Factory
tags pwm vintage warm
osc1Shape 3
osc2Shape 3
osc2Detune 0.1
osc2Level 0.5
filterCutoff 3200
filterReso 0.8
filterMode 0
amp 0.02 0.2 0.85 0.25
mod 0.02 0.4 0.3 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 0.9 1
warp1 4 0.4
warp2 4 0.6
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 9
route 3 5 0.35
route 3 6 -0.35
route 1 2 1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.5 4 12 0.25
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.45 0.5 0.18
)MUEW"},
    {"night-bloom", R"MUEW(muew-preset 2
name Night Bloom
category Pad
author MUEW Factory
tags evolving mseg dark
osc1Shape 2
osc2Shape 1
osc2Detune 0.07
osc2Level 0.55
filterCutoff 1800
filterReso 0.6
filterMode 0
amp 1.4 1.5 0.8 2.2
mod 1 1 0.5 1.5
lfo1Rate 0.2
lfo1Shape 0
lfo2 0.35 1
warp1 3 0.2
warp2 6 0
mseg 4 1 5 0 0 0.3 1 0.6 0.2 0.85 0.7 1 0
routes 9
route 4 5 0.5
route 4 2 1.3
route 0 3 0.12
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.3 6 14 0.3
delay 1 0.45 0.6 0.35 0.2
reverb 1 0.88 0.35 0.42
)MUEW"},
    {"vector-choir", R"MUEW(muew-preset 2
name Vector Choir
category Pad
author MUEW Factory
tags choir vocal wide
osc1Shape 1
osc2Shape 2
osc2Detune 0.05
osc2Level 0.4
filterCutoff 1100
filterReso 0.9
filterMode 1
amp 0.9 1 0.85 1.8
mod 0.8 1 0.5 1
lfo1Rate 0.25
lfo1Shape 1
lfo2 0.18 0
warp1 3 0.45
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 3 5 0.3
route 0 2 0.4
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.4 8 16 0.4
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.8 0.4 0.38
)MUEW"},
    {"frozen-lake", R"MUEW(muew-preset 2
name Frozen Lake
category Pad
author MUEW Factory
tags airy glassy cold
osc1Shape 0
osc2Shape 1
osc2Detune 12.03
osc2Level 0.35
filterCutoff 6500
filterReso 0.4
filterMode 0
amp 1.3 1 0.9 3
mod 1 1 0.5 1
lfo1Rate 0.1
lfo1Shape 0
lfo2 0.07 0
warp1 2 0
warp2 6 0.3
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 3 6 0.4
route 3 2 0.4
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.25 5 12 0.3
delay 1 0.5 0.66 0.45 0.25
reverb 1 0.93 0.3 0.45
)MUEW"},
    {"tidal-wash", R"MUEW(muew-preset 2
name Tidal Wash
category Pad
author MUEW Factory
tags sweep slow wide
osc1Shape 2
osc2Shape 3
osc2Detune -0.1
osc2Level 0.45
filterCutoff 1200
filterReso 1.1
filterMode 0
amp 1.6 1.5 0.85 2.5
mod 1 1 0.5 1
lfo1Rate 0.2
lfo1Shape 0
lfo2 0.06 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 3 2 2
route 0 3 0.15
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.3 6 14 0.3
delay 1 0.55 0.7 0.4 0.25
reverb 1 0.82 0.45 0.38
)MUEW"},
    {"prism-keys", R"MUEW(muew-preset 2
name Prism Keys
category Keys
author MUEW Factory
tags digital quantized bright
osc1Shape 2
osc2Shape 1
osc2Detune 12
osc2Level 0.35
filterCutoff 4500
filterReso 0.6
filterMode 0
amp 0.005 0.7 0.35 0.5
mod 0.005 0.6 0 0.3
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 5 0.55
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 5 -0.4
route 2 2 1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.35 3 10 0.2
delay 1 0.3 0.45 0.25 0.15
reverb 1 0.5 0.5 0.22
)MUEW"},
    {"velvet-ep", R"MUEW(muew-preset 2
name Velvet EP
category Keys
author MUEW Factory
tags electric-piano soft velocity
osc1Shape 0
osc2Shape 1
osc2Detune 0
osc2Level 0.35
filterCutoff 2800
filterReso 0.4
filterMode 0
amp 0.003 1.2 0.3 0.6
mod 0.003 0.8 0 0.4
lfo1Rate 4.5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0.1
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 2 2 1.5
route 1 6 0.4
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.8 2.5 8 0.25
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.45 0.55 0.18
)MUEW"},
    {"bell-tines", R"MUEW(muew-preset 2
name Bell Tines
category Keys
author MUEW Factory
tags bell metallic bright
osc1Shape 0
osc2Shape 0
osc2Detune 19.02
osc2Level 0.45
filterCutoff 8000
filterReso 0.4
filterMode 0
amp 0.001 1.8 0 1.4
mod 0.001 1.2 0 1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 6 0.15
warp2 1 0.2
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 5 0.6
route 1 6 0.3
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.37 0.5 0.3 0.2
reverb 1 0.7 0.35 0.3
)MUEW"},
    {"fold-pluck", R"MUEW(muew-preset 2
name Fold Pluck
category Pluck
author MUEW Factory
tags fold short percussive
osc1Shape 1
osc2Shape 0
osc2Detune 12
osc2Level 0.3
filterCutoff 4000
filterReso 0.8
filterMode 0
amp 0.001 0.3 0 0.2
mod 0.001 0.18 0 0.1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 6 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 5 0.9
route 1 2 1.5
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.25 0.37 0.3 0.2
reverb 1 0.4 0.5 0.15
)MUEW"},
    {"marimba-wood", R"MUEW(muew-preset 2
name Marimba Wood
category Pluck
author MUEW Factory
tags mallet wooden short
osc1Shape 1
osc2Shape 0
osc2Detune 12
osc2Level 0.25
filterCutoff 1400
filterReso 1.6
filterMode 0
amp 0.001 0.4 0 0.25
mod 0.001 0.1 0 0.1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 1.2
route 2 2 0.5
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 0 0.28 0.42 0.35 0.22
reverb 1 0.35 0.6 0.15
)MUEW"},
    {"echo-pluck", R"MUEW(muew-preset 2
name Echo Pluck
category Pluck
author MUEW Factory
tags delay rhythmic bright
osc1Shape 2
osc2Shape 3
osc2Detune 0.05
osc2Level 0.4
filterCutoff 3800
filterReso 0.7
filterMode 0
amp 0.001 0.25 0 0.2
mod 0.001 0.2 0 0.1
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 1 0 4 0 0 0.15 1 0.55 -0.3 1 0
routes 8
route 1 2 2.2
route 2 2 0.7
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.5 4 12 0.2
delay 1 0.375 0.25 0.5 0.35
reverb 1 0.55 0.45 0.2
)MUEW"},
    {"bent-circuit", R"MUEW(muew-preset 2
name Bent Circuit
category Texture
author MUEW Factory
tags glitch stepped mseg
osc1Shape 3
osc2Shape 2
osc2Detune -5
osc2Level 0.45
filterCutoff 2400
filterReso 1.5
filterMode 0
amp 0.005 0.3 0.85 0.4
mod 0.01 0.3 0 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 1.3 2
warp1 5 0.2
warp2 1 0.2
mseg 0.75 1 8 0 -1 0.2 -1 0.21 0.6 0.45 0.6 0.46 -0.2 0.7 -0.2 0.71 1 1 1
routes 9
route 4 5 0.7
route 4 2 1.2
route 3 6 0.3
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.18 0.27 0.45 0.3
reverb 1 0.55 0.4 0.25
)MUEW"},
    {"chrome-motion", R"MUEW(muew-preset 2
name Chrome Motion
category Texture
author MUEW Factory
tags rhythmic gated motion
osc1Shape 2
osc2Shape 4
osc2Detune 7
osc2Level 0.5
filterCutoff 2000
filterReso 1.3
filterMode 0
amp 0.01 0.3 0.9 0.5
mod 0.01 0.3 0 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 3 0.3
warp2 6 0
mseg 0.5 1 8 0 1 0.12 -0.6 0.25 1 0.37 -0.6 0.5 0.6 0.62 -0.6 0.75 1 1 -0.6
routes 9
route 4 3 0.5
route 4 2 1.6
route 0 5 0.1
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.4 5 12 0.3
delay 1 0.3 0.45 0.35 0.25
reverb 1 0.6 0.4 0.25
)MUEW"},
    {"rising-tide", R"MUEW(muew-preset 2
name Rising Tide
category FX
author MUEW Factory
tags riser sweep long
osc1Shape 2
osc2Shape 2
osc2Detune 0.2
osc2Level 0.6
filterCutoff 300
filterReso 2
filterMode 0
amp 0.5 1 1 2
mod 0.01 0.3 0 0.2
lfo1Rate 0.5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 6 0 3 0 0 0.9 1 1 1
routes 10
route 4 2 4.5
route 4 0 12
route 4 1 12
route 0 3 0.2
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 1 0.8 6 14 0.35
delay 1 0.4 0.55 0.4 0.25
reverb 1 0.85 0.35 0.4
)MUEW"},
    {"laser-drop", R"MUEW(muew-preset 2
name Laser Drop
category FX
author MUEW Factory
tags drop zap pitch
osc1Shape 2
osc2Shape 3
osc2Detune 0
osc2Level 0.4
filterCutoff 5000
filterReso 2.5
filterMode 0
amp 0.001 0.6 0 0.3
mod 0.001 0.4 0 0.2
lfo1Rate 5
lfo1Shape 0
lfo2 0.35 1
warp1 2 0
warp2 6 0
mseg 0.4 0 3 0 1 0.3 0.1 1 -1
routes 9
route 4 0 24
route 4 1 24
route 4 2 1.5
route 5 2 3
route 6 5 0.7
route 6 6 0.7
route 7 4 4
route 8 1 0.3
route 8 3 0.25
chorus 0 0.6 6 15 0.35
delay 1 0.2 0.3 0.4 0.25
reverb 1 0.5 0.5 0.2
)MUEW"},
};

constexpr int kFactoryPresetCount = (int)(sizeof(kFactoryPresetTexts) / sizeof(kFactoryPresetTexts[0]));

// Parsed once on first use (never on the audio thread).
inline const std::vector<Preset>& factoryPresets() {
    static const std::vector<Preset> bank = [] {
        std::vector<Preset> v;
        for (const auto& t : kFactoryPresetTexts) { Preset p; p.parse(t.text); v.push_back(p); }
        return v;
    }();
    return bank;
}

// Browser category order shown in the UI.
inline const std::vector<std::string>& factoryCategories() {
    static const std::vector<std::string> c{"Bass", "Lead", "Pad", "Keys", "Pluck", "Texture", "FX"};
    return c;
}

} // namespace muew
